include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_relative_imports: true
    # prefer_single_quotes: true

# Additional information about this file can be found at
# https://dart-lang.github.io/linter/lints/index.html.
# https://dart.dev/guides/language/analysis-options
